CreateMutli/Models/Page.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CreateMutli.Models
{
    public class Page
    {

            [Required]
            public string Pages { get; set; }

           
        }
    
    
    }

CreateMutli/Controllers/MultiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CreateMutli.Models;

namespace CreateMutli.Controllers
{
    public class MultiController : Controller
    {
        //
        // GET: /Multi/
 public ActionResult Index()
        {
            return View();
        }
       

    
     public ActionResult CreateMutli()
        {
            var pages = new List<Page>();
            return View(pages);
        }

        public ActionResult AddPage(List<Page> pages)
        {
            if (pages == null)
                pages = new List<Page> { };
            ModelState.Clear();
            pages.Add(new Page { });
            return View("CreateMutli", pages);
}

        public ActionResult RemovePage(List<Page> pages, int id)
        {
            ModelState.Clear();
            pages.RemoveAt(id);
            return View("CreateMutli", pages);
        }

        [HttpPost]
        public ActionResult CreateMutli(List<Page> pages)
        {
            return View(pages);
        }

    }







}

CreateMutli/Views/Multi/CreateMutli.cshtml
@model List<CreateMutli.Models.Page>



@{
    ViewBag.Title = "CreateMutli";
}

<h2>Create Mutliple Pages</h2>

 
@using (Html.BeginForm("CreateMutli", "Multi"))
{
    @Html.ActionLink("Add", "AddPage", null, new { @class="post-link"})
    <ul>
       @for (var counter = 0; counter < Model.Count; counter++ )
        {
            <li>
                @Html.TextBoxFor(model => Model[counter].Pages)
                @Html.ActionLink("x", "RemovePage", new { id = counter }, new { @class = "post-link" })
            </li>
        }

    </ul>
    <input type="submit" value="save" />    
}

@section scripts{
   <script>
       $(".post-link").click(function () {
           var form = $(this).parents("form");
           form.attr("action", this.href);
           form.submit();
           return false;
       });
   </script>
}

CreateMutli/Views/Multi/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


 @Html.ActionLink("CreateMutli", "CreateMutli")

CreateMutli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>